@startuml
'https://plantuml.com/class-diagram

class TodoApp extends Application {
    +void main()
    +void start(Stage)
}

class TodoAppController implements Initializable {
    -TodoItem[] todoItems
    -TodoItem[] todoItemsInView
    '0 = All, 1 = Complete only, 2 = Incomplete only
    -int viewOption
    +void initialize(URL, ResourceBundle)
    +void onCloseClick(ActionEvent action)
    +void redrawList()
    +void toggleFilter(ActionEvent action)
    +void addItem()
    +void removeItem()
    +void removeAllItems()
    +void changeItemDescription()
    +void changeItemDueDate()
    +void toggleItemCompletion()
    +void openHelpDialogue()
    +void importItems()
    +void exportItems()
}

class TodoItem {
    -String description
    -Date dueDate
    -Boolean isComplete
    +TodoItem(String description, Date dueDate)
    +String getDescription()
    +void setDescription(String)
    +Date getDate()
    +void setDate(Date)
    +Boolean getIsComplete()
    +void setIsComplete(Boolean)
}

TodoApp *-- TodoAppController
TodoAppController *- TodoItem

@enduml